#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
unlink ("$datadir/rsyslog");
unlink ("$datadir/rsyslog.err");

my $result = gauntletRunCommand($hostname, 'ps -eaf | grep rsyslog | grep -v grep', "rsyslog");
# log our results to stdout and return an exit status 
if (! $result) {
	print `head $datadir/rsyslog`;
} else {
	if (-z "$datadir/rsyslog") {
		print "No rsyslog processes\n";
		exit 1;
	}
	print `cat $datadir/rsyslog.err`;
}
exit ($result); 
