#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
unlink ("$datadir/apache2");
unlink ("$datadir/apache2.err");

my $result = gauntletRunCommand($hostname, 'ps -eaf | grep apache2 | grep -v grep', "apache2");
# log our results to stdout and return an exit status 
if (! $result) {
	print `head $datadir/apache2`;
} else {
	if (-z "$datadir/apache2") {
		print "No apache2 processes\n";
		exit $status;
	}
	print `cat $datadir/apache2.err`;
}
exit ($result); 
