#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
unlink ("$datadir/lcfd");
unlink ("$datadir/lcfd.err");

my $result = gauntletRunCommand($hostname, 'ps -eaf | grep lcfd | grep -v grep', "lcfd");
# log our results to stdout and return an exit status 
if (! $result) {
	print `head $datadir/lcfd`;
} else {
	if (-z "$datadir/lcfd") {
		print "No lcfd processes\n";
		exit $status;
	}
	print `cat $datadir/lcfd.err`;
}
exit ($result); 
