#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
my $result = gauntletRunCommand($hostname, 'ls -l /etc/alternatives/mta', "whichmta");
# log our results to stdout and return an exit status 
if (! $result) {
	my $line = `head $datadir/whichmta`;
	chomp $line;
	if ($line =~ /\/usr\/sbin\/sendmail.(\S+)/) {
		print $1, "\n";
	} else {
		print $line, "\n";
	}
} else {
	print `cat $datadir/whichmta.err`;
}
exit ($result); 
