#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
my $result = gauntletRunCommand($hostname, 'ntpq -c peers', "ntp_chk");
# log our results to stdout and return an exit status 
if (! $result) {
	print `head $datadir/ntp_chk`;
} else {
	print `cat $datadir/ntp_chk.err`;
}
exit ($result); 
