#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
unlink ("$datadir/java");
unlink ("$datadir/java.err");

my ($os, $arch) = gauntletHostArch($hostname);
if (!$os) {
	print `cat $datadir/hostinfo.err`;
	exit 1;
} else {
	print "Remote host $hostname is running: $os on $arch\n" if ($DEBUG);
}
my $result = gauntletRunCommand($hostname, 'ps -eaf | grep java | grep -v grep', "java");
# log our results to stdout and return an exit status 
if (! $result) {
	print `head $datadir/java`;
} else {
	if (-z "$datadir/java") {
		print "No java processes\n";
		exit 1;
	}
	print `cat $datadir/java.err`;
}
exit ($result); 
