#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
unlink ("$datadir/java");
unlink ("$datadir/java.err");

my $result = gauntletRunCommand($hostname, 'ps -eaf | grep java | grep -v grep', "java");
# log our results to stdout and return an exit status 
if (! $result) {
	print `head $datadir/java`;
} else {
	if (-z "$datadir/java") {
		print "No java processes\n";
		exit $status;
	}
	print `cat $datadir/java.err`;
}
exit ($result); 
