#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
my $result = gauntletRunCommand($hostname, 'cat /etc/redhat-release', "redhat-release");
# log our results to stdout and return an exit status 
if (! $result) {
	print `cat $datadir/redhat-release`;
} else {
	print `tail -1 $datadir/redhat-release.err`;
}
exit ($result); 
