#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
my $result = gauntletRunCommand($hostname, 'mailq', "mailq");
# log our results to stdout and return an exit status 
if (! $result) {
	my $output = `tail -1 $datadir/mailq`;
	if ($output =~ /in (\S+) Requests/) {
		print $1, "\n";
		exit $1;
	}
	if ($output =~ /Total requests: (\S+)/) {
		print $1, "\n";
		exit $1;
	}
	if ($output =~ /Mail queue is empty/ ) {
		print "0\n";
		exit 0;
	}
} else {
	print `cat $datadir/mailq.err`;
}
exit ($result); 
