#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
# takes: hostname, filename, dstfilename
my $result = gauntletCopyFile($hostname, "/etc/snmp/snmpd.conf", "snmpd.conf");
my $result = gauntletRunCommand($hostname, 'cksum /etc/snmp/snmpd.conf', "cksum-snmpd.conf");

# log our results to stdout and return an exit status 
if (! $result) {
	print `cat $datadir/cksum-snmpd.conf`;
} else {
	print `tail -1 $datadir/cksum-snmpd.conf.err`;
}
exit ($result); 
