#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
unlink ("$datadir/cfexecd");
unlink ("$datadir/cfexecd.err");

my $result = gauntletRunCommand($hostname, 'grep -v "^#" /etc/cron.d/cfexecd', "cfexecd");
# log our results to stdout and return an exit status 
if (! $result) {
	print `head $datadir/cfexecd`;
} else {
	if (-z "$datadir/cfexecd") {
		print "No cfexecd cron entry\n";
		exit 1;
	}
	print `cat $datadir/cfexecd.err`;
}
exit ($result); 
