#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
my $result = gauntletRunCommand($hostname, 'xm list | awk \'{ print \$1 }\' | egrep -v \'Name|Domain-0\'', "xen-basic");
$result =~ s/^\s+//;
# log our results to stdout and return an exit status 
if (! $result) {
	print `cat $datadir/xen-basic`;
} else {
	print `tail -1 $datadir/xen-basic.err`;
}
exit ($result); 
