#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
#my $result = gauntletRunCommand($hostname, 'cat /etc/sysconfig/network/route-eth\* egrep -v \'10.2.134|10.8.0\'', "check-redhat-customroutes");
my $result = gauntletRunCommand($hostname, 'cat /etc/sysconfig/network/route-eth\* | egrep -v \'10.2.134|10.8.0\'', "check-redhat-customroutes");
# log our results to stdout and return an exit status 
if (! $result) {
	print `cat $datadir/check-redhat-customroutes`;
} else {
	print `tail -1 $datadir/check-redhat-customroutes.err`;
}
exit ($result); 
