#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
unlink ("$datadir/appevai");
unlink ("$datadir/appevai.err");

my $result = gauntletRunCommand($hostname, 'ps -eaf | grep appevai | grep -v grep', "appevai");
# log our results to stdout and return an exit status 
if (! $result) {
	print `head $datadir/appevai`;
} else {
	if (-z "$datadir/appevai" && -z "$datadir/appevai.err") {
		print "No appevai processes\n";
		exit $status;
	}
	print `cat $datadir/appevai.err`;
}
exit ($result); 
