#!/usr/bin/perl -I/ebay/gauntlet/lib

use Audit;

$hostname = shift;
chomp $hostname;

#$DEBUG = 1;

if (! $hostname) {
	print "Usage: $0 <hostname>\n";
	exit 2;
}
#print "Auditing host: $hostname\n";

my $datadir = getHostDataDir($hostname);
$result = gauntletRunCommand($hostname, 'grep ldap /etc/nsswitch.conf | grep -v \"^#\"', "check-ldap-nsswitch");

# log our results to stdout and return an exit status 
if (! $result) {
	print `head $datadir/check-ldap-nsswitch`;
} else {
	print `cat $datadir/check-ldap-nsswitch.err`;
}
exit ($result); 
